name = "test-mcp-server"
main = "./worker.ts"
compatibility_date = "2025-05-13"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "TestMcpAgent"

 [[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["TestMcpAgent"]
